name: Branch-wise Deployment

on:
  push:
    branches:
      - main
      - sandbox
      - quality

jobs:
  deployproduction:
    if: github.ref == 'refs/heads/main'  
    uses: banmcr/workflowrepo/.github/workflows/reusable-workflow2.yml@main
    with:
      environment: "Production"
      Region: "us-east-2"
    secrets:
      CONNAPPCLIENTID: ${{ secrets.PRDCONNAPPCLIENTID }}
      CONNAPPCLIENTSECRET : ${{ secrets.PRDCONNAPPCLIENTSECRET }}
      CLIENTID : ${{ secrets.PRDCLIENTID }}
      CLIENTSECRET : ${{ secrets.PRDCLIENTSECRET }}

  deployquality:
    if: github.ref == 'refs/heads/quality'
    uses: banmcr/workflowrepo/.github/workflows/reusable-workflow2.yml@main
    with:
      environment: "Quality"
      Region: "us-east-2"
    secrets:
      CONNAPPCLIENTID: ${{ secrets.QAULITYCONNAPPCLIENTID }}
      CONNAPPCLIENTSECRET : ${{ secrets.QAULITYCONNAPPCLIENTSECRET }}
      CLIENTID : ${{ secrets.QAULITYCLIENTID }}
      CLIENTSECRET : ${{ secrets.QAULITY  CLIENTSECRET }}

  deploysandbox:
    if: github.ref == 'refs/heads/quality'
    uses: banmcr/workflowrepo/.github/workflows/reusable-workflow2.yml@main
    with:
      environment: "Sandbox"
      Region: "us-east-2"
    secrets:
      CONNAPPCLIENTID: ${{ secrets.SANDBOXCONNAPPCLIENTID }}
      CONNAPPCLIENTSECRET : ${{ secrets.SANDBOXCONNAPPCLIENTSECRET }}
      CLIENTID : ${{ secrets.SANDBOXCLIENTID }}
      CLIENTSECRET : ${{ secrets.SANDBOXCLIENTSECRET }}
