name: Branch-wise Deployment

on:
  push:
    branches:
      - main
      - sandbox
      - quality

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - main
          - quality

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Reusable Workflow
      if: matrix.branch == 'main'
      uses: banmcr/workflowrepo/.github/workflows/reusable-workflow2.yml@main
      with:
        my_variable: ${{ secrets.mainVAR1 }}
        my_secret: ${{ secrets.mainSEC1 }}

    - name: Reusable Workflow
      if: matrix.branch == 'quality'
      uses: banmcr/workflowrepo/.github/workflows/reusable-workflow2.yml@main
      with:
        my_variable: ${{ secrets.quaVAR1 }}
        my_secret: ${{ secrets.quaSEC1 }}
